config/routes.rb
Rails.application.routes.draw do

  root to: 'mcs#index'
  resources :mcs do
   post 'take_out' => 'mcs#take_out'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mc.rb
class Mc < ApplicationRecord
  has_many :take_outs, dependent: :destroy
end

app/models/take_out.rb
class TakeOut < ApplicationRecord
  belongs_to :mc
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mcs_controller.rb
class McsController < ApplicationController

  def new
    @mc = Mc.new
  end

  def create
    @mc = Mc.new(mc_params)
    @mc.save
    redirect_to mcs_path
  end

  def take_out
    @take = TakeOut.new(take_out_params)
    @take.save
    redirect_to mcs_path
  end

  def index
    @mcs = Mc.all
  end

  def show
  end

  def edit
    @mc = Mc.find(params[:id])
  end

  def update
    @mc = Mc.find(params[:id])
    @mc.update(mc_params)
    redirect_to mcs_path
  end

  def destroy
  end

  private

  def mc_params
    params.require(:mc).permit(:item_name, :quantity, :limit)
  end

  def take_out_params
    params.permit(:name, :take)
  end

end

app/controllers/take_outs_controller.rb
class TakeOutsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mcs_helper.rb
module McsHelper
end

app/helpers/take_outs_helper.rb
module TakeOutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Keisan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mcs/edit.html.erb
<%= form_with model:@mc,url: mc_path(@mc), method: :patch, local: true do |f| %>
 <%= f.text_field :quantity %>
 <%= f.submit "変更"%>
<% end %>

app/views/mcs/index.html.erb
<h1>一覧</h1>
<%= link_to "", new_mc_path, class: "fas fa-plus fa-2x" %>
<div>
 <% @mcs.each do |mc| %>
 <div>
  <%= form_with model:@take,url: mc_take_out_path(mc), local: true do |f| %>
   <%= f.text_field :name %>
   <%= f.text_field :take %>
   <%= f.submit "取り出し"%>
  <% end %>
  <%= mc.item_name %>
  <%= mc.quantity %>
  <%= link_to "編集", edit_mc_path(mc) %>
 </div>
 <% end %>
</div>

app/views/mcs/new.html.erb
新規登録
<%= form_with model:@mc,url: mcs_path, method: :post , local:true do |f| %>
 <%= f.label "商品名" %>
 <%= f.text_field :item_name %>
 <%= f.label "在庫"%>
 <%= f.text_field :quantity %>
 <%= f.label "最低個数"%>
 <%= f.text_field :limit %>
<%= f.submit "登録"%>
<% end %>

<%= link_to "一覧画面へ", mcs_path %>